### ISSUE TITLE
feat(site): update site content to avoid blatant "inaccurate information"

### ISSUE THREAD

**Issue by EnokiUN** [eludris/elusite#7]
Modify the home page to include some actual features Eludris offers instead of old bogus

**Comment by Sharp-Eyes** [comment]
no

**Comment by EnokiUN** [comment]
> no

what

**Comment by Sharp-Eyes** [comment]
Closed as intended behaviour.

**Comment by Sharp-Eyes** [comment]
thanks eric

**Comment by EnokiUN** [comment]
no please

**Comment by EnokiUN** [comment]
I will play arknights if you close this again

**Comment by Sharp-Eyes** [comment]
@everyone we are never closing this issue.

**Comment by EnokiUN** [comment]
gtg play arknights
